---
title: "WASP"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{WASP}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(rmarkdown)
library(knitr)
library(kableExtra)
```

```{r setup}
library(WASP)
library(testthat)
```

```{r wavelet-transforms}
  # data generation
  x <- arima.sim(list(order = c(1,0,0), ar = 0.6), n = 512)
  x <- as.numeric(scale(data.gen.Rossler(time = seq(0, 50, length.out = 512))$x, scale=F))

  #for(wf in c("mb4","w4","bs3.1")){ #not working
  for(wf in c("haar","d4","d8","d16", "fk4","la8","bl14")){ #working ones
    print(paste0("Wavelet filter: ", wf))
    #----------------------------------------------------------------------------
    # wavelet family, extension mode and package
    #wf <- "haar" # wavelet family D8 or db4
    boundary <- "periodic"
    if(wf!="haar") v <- as.integer(readr::parse_number(wf)/2) else v <- 1

    #Maximum decomposition level J
    n <- length(x)
    J <- ceiling(log(n/(2*v-1))/log(2))-1 #(Kaiser, 1994)
    
    cov = rnorm(J+1, sd=2); Vr <- as.numeric(cov/norm(cov,type="2")*sd(x))
    #----------------------------------------------------------------------------
    #DWT-MRA
    print("-----------DWT-MRA-----------")
    x.mra <- waveslim::mra(x,wf=wf, J=J, method="dwt", boundary=boundary)
    x.mra.m <- matrix(unlist(x.mra), ncol=J+1)
    
    x.n <- scale(x.mra.m)%*%Vr; var(x.n)-var(x)

    message(paste0("Additive decompostion: ", isTRUE(all.equal(as.numeric(x),rowSums(x.mra.m)))))
    message(paste0("Variance decompostion: ", isTRUE(all.equal(var(x),sum(apply(x.mra.m,2,var))))))

    #----------------------------------------------------------------------------
    #MODWT
    print("-----------MODWT-----------")
    x.modwt <- waveslim::modwt(x, wf=wf, n.levels = J, boundary = boundary)
    x.modwt.m <- matrix(unlist(x.modwt), ncol=J+1)
    
    x.n <- scale(x.modwt.m)%*%Vr; var(x.n)-var(x)
    
    message(paste0("Additive decompostion: ", isTRUE(all.equal(as.numeric(x),rowSums(x.modwt.m)))))
    message(paste0("Variance decompostion: ", isTRUE(all.equal(var(x),sum(apply(x.modwt.m,2,var))))))

    #----------------------------------------------------------------------------
    #a trous
    print("-----------AT-----------")
    x.at <- at.wd(x, wf=wf, J=J, boundary=boundary)
    x.at.m <- matrix(unlist(x.at), ncol=J+1)

    message(paste0("Additive decompostion: ", isTRUE(all.equal(as.numeric(x),rowSums(x.at)))))
    message(paste0("Variance decompostion: ", isTRUE(all.equal(var(x),sum(apply(x.at,2,var))))))

    if(isTRUE(all.equal(x.at.m,x.modwt.m))) message(paste0("AT and MODWT is equivalent using ", wf))

  }
  
```

```{r optimal-variance-transformation, warning=TRUE}
if(TRUE){
###Synthetic example
#data generation
set.seed(2020)
sample = 512
#frequency, sampled from a given range
fd <- c(3,5,10,15,25,30,55,70,95)
#data <- data.gen.SW(nobs=sample,fp=25,fd=fd)
data <- data.gen.SW(nobs=sample,fp=c(15,25,30),fd=fd)

ts = data.gen.Rossler(time = seq(0, 50, length.out = sample))
data <- list(x=ts$z, dp=cbind(ts$x, ts$y))

} else {
###Real-world example
data("obs.mon"); data("rain.mon")

if(1){ #SPI12 as response
  SPI.12 <- SPEI::spi(rain.mon[,5],scale=12)$fitted
  x <- window(SPI.12,start=c(1950,1),end=c(2009,12))
  dp <- window(obs.mon,start=c(1950,1),end=c(2009,12))
  
} else {#rainfall as response
  x <- window(rain.mon[,5],start=c(1950,1),end=c(2009,12))
  dp <- window(obs.mon,start=c(1950,1),end=c(2009,12))
}
data <- list(x=x,dp=dp)
sample=length(x)

}

#plot.ts(cbind(data$x,data$dp))

tab.list <- list()
mode.opts <- c("MRA", "MODWT","AT")
for(mode in mode.opts){
  print(mode)
  
  #cov.opt <- switch(2,"auto","pos","neg")
  if(mode=="MRA") method <- switch(1,"dwt","modwt")
  
  # wavelet family, extension mode and package
  #wf <- switch(mode, "MRA"="haar", "MODWT"="haar", "AT"="haar")
  wf="haar"
  pad="zero"
  boundary <- "periodic"
  if(wf!="haar") v <- as.integer(readr::parse_number(wf)/2) else v <- 1
  
  #Maximum decomposition level J
  n <- sample
  J <- ceiling(log(n/(2*v-1))/log(2))-1 #(Kaiser, 1994)
  
  tab <- NULL
  for(cov.opt in c("auto","pos","neg")){
    # variance transfrom - calibration
    if(mode=="MRA"){
      dwt<- dwt.vt(data, wf, J, method, pad, boundary, cov.opt)
    } else if(mode=="MODWT") {
      dwt<- modwt.vt(data, wf, J, boundary, cov.opt)
    } else {
      dwt<- at.vt(data, wf, J, boundary, cov.opt)
    }
    
    # optimal prediction accuracy
    opti.rmse <- NULL
    dp.RMSE <- NULL; dp.n.RMSE <- NULL
    S <- dwt$S; ndim=ncol(S)
    for(i in 1:ndim){
      x <- dwt$x
      dp <- dwt$dp[,i]
      dp.n <- dwt$dp.n[,i]
      
      #ts.plot(cbind(dp,dp.n), col=1:2)
  
      dp.RMSE <- c(dp.RMSE, sqrt(mean(lm(x~dp)$residuals^2)))
      dp.n.RMSE <- c(dp.n.RMSE, sqrt(mean(lm(x~dp.n)$residuals^2)))
  
      #small difference due to the reconstruction
      opti.rmse <- c(opti.rmse, sqrt((n-1)/n*(var(x)-sum(S[,i]^2)*var(dp)/var(dp.n)))) 
      #opti.rmse <- c(opti.rmse, sqrt((n-1)/n*(var(x)-sum(S[,i]^2))))
    }
  
  tab <- rbind(tab, cbind(dp.RMSE, dp.n.RMSE, opti.rmse))
  }
  
  rownames(tab) <- rep(c("auto","pos","neg"),each=ndim)
  tab.list[[length(tab.list)+1]] <- tab
} 

print(tab.list)

```

```{r high-order-transformation}
#-------------------------------------------------------------------
###Real-world example
data("obs.mon"); data("rain.mon")
station.id = 5
lab.names <- colnames(obs.mon)[c(1,3,4,5,7)]

if(1){ #SPI12 as response
  SPI.12 <- SPEI::spi(rain.mon,scale=12)$fitted
  x <- window(SPI.12,start=c(1950,1),end=c(2009,12))
  dp <- window(obs.mon[,lab.names],start=c(1950,1),end=c(2009,12))
  
} else {#rainfall as response
  x <- window(rain.mon,start=c(1950,1),end=c(2009,12))
  dp <- window(obs.mon[,lab.names],start=c(1950,1),end=c(2009,12))
  
}

data.list <- lapply(station.id, function(id) list(x=x[,id],dp=dp))


ylim=data.frame(GPH=c(700,900),TDP700=c(5,25),TDP500=c(5,25),EPT=c(300,330),
                UWND=c(-5,25),VWND=c(-5,10),MSLP=c(-1, 1))[c(1,3,4,5,7)]

#-------------------------------------------------------------------
p.list <- list(); RMSE <- NULL
mode.opts <- c("MRA", "MODWT","AT")[1:2]
for(mode in mode.opts){
  
  cov.opt <- switch(1,"auto","pos","neg")
  if(mode=="MRA") method <- switch(1,"dwt","modwt")
  
  # wavelet family, extension mode and package
  wf <- switch(mode, "MRA"="d4", "MODWT"="haar", "AT"="haar")
  pad="zero"
  boundary <- "periodic"
  if(wf!="haar") v <- as.integer(readr::parse_number(wf)/2) else v <- 1
  
  # Maximum decomposition level J
  n <- nrow(x)
  J <- ceiling(log(n/(2*v-1))/log(2)) - 1 #(Kaiser, 1994)
  
  # high order variance transfromation
  dwt.list = lapply(data.list, function(data) stepwise.VT(data, mode=mode, wf=wf))
  
  for(j in 1:length(dwt.list)){
    dwt <- dwt.list[[j]]
    cpy <- dwt$cpy
    
    MSE <- NULL
    for(i in 1:length(cpy)){
      m1 <- sqrt(FNN::knn.reg(train=dwt$dp[,1:i], y=dwt$x)$PRESS/n)
      m2 <- sqrt(FNN::knn.reg(train=dwt$dp.n[,1:i], y=dwt$x)$PRESS/n)
      
      MSE <- rbind(MSE, c(m1,m2))
    }
    
    RMSE <- cbind(RMSE, MSE)
    
    par(mfrow=c(ncol(dp),1),mar=c(0,4,2,1),
        oma = c(2, 1, 0, 0), # move plot to the right and up
        mgp=c(1.5, 0.5, 0), # move axis labels closer to axis
        pty="m",bg = "transparent",
        ps=8)
    
    #plot(dwt$x, type="l", xlab=NA, ylab="SPI12", ylim=c(-3,3),col="red")
    #plot(dwt$x, type="l", xlab=NA, ylab="Rain", col="red")
    for(i in 1:ncol(dp))
      ts.plot(dwt$dp[,i],dwt$dp.n[,i],xlab=NA,ylab=paste0(lab.names[cpy[i]]), #ylim=ylim[,i],
              col=c("black","blue"),lwd=c(1,2))
    
    p.list[[length(p.list)+1]] <- recordPlot()
    
  }
}

#-------------------------------------------------------------------
#plot and save
cowplot::plot_grid(plotlist =p.list, nrow=1, labels= c("(a)","(b)","(c)"))

#-------------------------------------------------------------------
#RMSE when more predictors are included
tab1 <- round(RMSE,3)
tab1 <- cbind(1:nrow(tab1), tab1)
colnames(tab1) <- c("No. of Predictors", rep(c("Original","Transformed"), length(mode.opts)))

kable(tab1, caption = "Comparison of prediction accuracy using both original and transformed high order predictors", booktabs = T) %>%
  kable_styling(latex_options = c("HOLD_position"),position = "center") %>%
#  add_header_above(c(" " = 1, "DWT-MRA" = 2, "MODWT" = 2, "AT" = 2))
  add_header_above(c(" " = 1, "DWT-MRA" = 2, "MODWT/AT" = 2)) 
```






